PREFIX ns: <http://aksw.org/mclient/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  ?iri
    rdfs:label ?title ;
    eg:url ?url ;
    eg:type ?type ;
    eg:nuts ?nuts ;
    eg:accountable ?accountable ;
    eg:email ?email ;
    eg:dcatApApi ?dcatApApi; 
	eg:technology ?technology;
	eg:openApi ?api;
	rdfs:comment ?comment; 
	eg:crawl ?crawl .
	
    
}
WHERE {
  <opendataportals-2.csv> csv:parse (?row "excel -h")
  BIND(json:path(?row, '$.portal_title') AS ?title)
  BIND(json:path(?row, '$.url') AS ?url)
  BIND(IRI(CONCAT(STR(ns:), ENCODE_FOR_URI(?title))) AS ?iri)
  BIND(json:path(?row, '$.type') AS ?type)
  BIND(json:path(?row, '$.technology') AS ?technology)
  BIND(json:path(?row, '$.open_api') AS ?api)
  BIND(json:path(?row, '$.comment') AS ?comment)
  BIND(json:path(?row, '$.crawl') AS ?crawl)


  BIND(json:path(?row, '$.nuts') AS ?nuts)
  BIND(json:path(?row, '$.accountable') AS ?accountable)
  BIND(json:path(?row, '$.email') AS ?email)

  BIND(json:path(?row, '$.dcat_ap_de') AS ?dcat_ap_de)
  BIND(IF(?dcat_ap_de = "", 1 = "a", IRI(?dcat_ap_de)) AS ?dcatApApi)
}

