PREFIX eg: <http://www.example.org/>

SELECT DISTINCT ?url ?label

WHERE {

	?portal eg:url ?url ;
		rdfs:label ?label ;
		eg:technology ?technology ;
		eg:crawl ?crawl .
	FILTER (regex(?technology, ?type, "i"))
	FILTER (?crawl = "1")
BIND(sys:getenv('PORTAL_TYPE') as ?type)
}
