prefix dcat:   <http://www.w3.org/ns/dcat#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix dct: <http://purl.org/dc/terms/> 

select ?date WHERE {

?dataset a dcat:Dataset .
?dataset dct:issued ?date .
}
OFFSET $MAPPING
LIMIT 10000
